create index IX_430D791F on BlogsEntry (companyId, displayDate);
create index IX_8CACE77B on BlogsEntry (companyId, userId);
create unique index IX_D05A3CBC on BlogsEntry (groupId, ctCollectionId, externalReferenceCode[$COLUMN_LENGTH:75$]);
create unique index IX_D6281CFE on BlogsEntry (groupId, ctCollectionId, urlTitle[$COLUMN_LENGTH:255$]);
create unique index IX_EFD75733 on BlogsEntry (groupId, ctCollectionId, uuid_[$COLUMN_LENGTH:75$]);
create index IX_621E19D on BlogsEntry (groupId, displayDate);
create index IX_31865B77 on BlogsEntry (groupId, status, displayDate);
create index IX_1E000A7D on BlogsEntry (groupId, status, userId, displayDate);
create index IX_FBDE0AA3 on BlogsEntry (groupId, userId, displayDate);
create index IX_7B596F05 on BlogsEntry (status, companyId, displayDate);
create index IX_D1CC59D5 on BlogsEntry (status, companyId, userId);
create index IX_67121F73 on BlogsEntry (status, displayDate);
create index IX_69157A4D on BlogsEntry (uuid_[$COLUMN_LENGTH:75$]);