/**
 * SPDX-FileCopyrightText: (c) 2000 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

export enum PartnerOpportunitiesColumnKey {
	ACCOUNT_NAME = 'ACCOUNT-NAME',
	ACTIVE = 'ACTIVE',
	CLOSE_DATE = 'CLOSE-DATE',
	CREATED_DATE = 'CREATED-DATE',
	CURRENCY = 'CURRENCY',
	OPPORTUNITY = 'OPPORTUNITY',
	GROWTH_ARR = 'GROWTH-ARR',
	HAS_RENEWAL = 'HAS-RENEWAL',
	LIFERAY_REP = 'LIFERAY-REP',
	PARTNER_ACCOUNT_NAME = 'PARTNER-ACCOUNT-NAME',
	PARTNER_NAME = 'PARTNER-NAME',
	PARTNER_REP_EMAIL = 'PARTNER-REP-EMAIL',
	PARTNER_REP_NAME = 'PARTNER-REP-NAME',
	STAGE = 'STAGE',
	SUBSCRIPTION_ARR = 'SUBSCRIPTION-ARR',
	SUBSCRIPTION_TERM = 'SUBSCRIPTION-TERM',
	TYPE = 'TYPE',
}
